"""Add vat_subject to Actor

Revision ID: 1279e51021f7
Revises: 2d08de55e3c9
Create Date: 2025-12-03 13:22:27.338417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1279e51021f7'
down_revision = '2d08de55e3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('vat_subject', sa.Boolean(), nullable=True))
    op.execute("UPDATE actor SET vat_subject = false")
    op.alter_column('actor', 'vat_subject', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'vat_subject')
    # ### end Alembic commands ###
