"""add_seller_fee_rate_to_auction

Revision ID: 2d08de55e3c9
Revises: cd7f7c40f9c3
Create Date: 2025-12-02 17:32:35.990744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d08de55e3c9'
down_revision = 'cd7f7c40f9c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('seller_fee_rate', sa.Float(), nullable=False, server_default='0.05'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'seller_fee_rate')
    # ### end Alembic commands ###
