"""add number to auction

Revision ID: 580848cf0121
Revises: c6a89afbc2ad
Create Date: 2025-12-03 16:06:06.008262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580848cf0121'
down_revision = 'c6a89afbc2ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'auction', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auction', type_='unique')
    op.drop_column('auction', 'number')
    # ### end Alembic commands ###
