"""Add hammer_price and ANOMALIE status

Revision ID: 812a13ad9614
Revises: 0ae4433aa4ed
Create Date: 2025-12-01 22:54:17.875565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812a13ad9614'
down_revision = '0ae4433aa4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('hammer_price', sa.Integer(), nullable=True))
    op.alter_column('lot', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lot', 'hammer_price')
    # ### end Alembic commands ###
