"""Add Invoice model and update Auction

Revision ID: 90a2ee7078b2
Revises: 812a13ad9614
Create Date: 2025-12-01 22:59:17.827774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a2ee7078b2'
down_revision = '812a13ad9614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('total_excl', sa.Float(), nullable=False),
    sa.Column('total_vat', sa.Float(), nullable=False),
    sa.Column('total_incl', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', name='invoicestatus'), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('signature_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_number'), 'invoice', ['number'], unique=True)
    op.add_column('auction', sa.Column('buyer_fee_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'buyer_fee_rate')
    op.drop_index(op.f('ix_invoice_number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
