"""Add siren_siret to Actor

Revision ID: c6a89afbc2ad
Revises: e10c23cb07ad
Create Date: 2025-12-03 13:38:24.579874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a89afbc2ad'
down_revision = 'e10c23cb07ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('siren_siret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'siren_siret')
    # ### end Alembic commands ###
