"""Add Settlement model and update Actor

Revision ID: cd7f7c40f9c3
Revises: c63fe6a7ede2
Create Date: 2025-12-01 23:03:43.911639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7f7c40f9c3'
down_revision = 'c63fe6a7ede2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', name='settlementstatus'), nullable=False),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_id'), 'settlement', ['id'], unique=False)
    op.add_column('actor', sa.Column('iban', sa.String(), nullable=True))
    op.add_column('actor', sa.Column('bic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'bic')
    op.drop_column('actor', 'iban')
    op.drop_index(op.f('ix_settlement_id'), table_name='settlement')
    op.drop_table('settlement')
    # ### end Alembic commands ###
