"""Add phone_number to Actor

Revision ID: e10c23cb07ad
Revises: 1279e51021f7
Create Date: 2025-12-03 13:32:23.954582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10c23cb07ad'
down_revision = '1279e51021f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'phone_number')
    # ### end Alembic commands ###
